#!/bin/bash

function print_usage {
cat <<EOF

Usage:
`basename $0`               Run all tests and generate coverage report
`basename $0` -f <feature>  Run tests for a single feature
`basename $0` -h            Show this page

EOF
exit $1
}

while getopts "hf:" OPT; do
  case $OPT in
    h) print_usage 0;;
    f) TEST_FEATURE="$OPTARG";;
    [?]) print_usage 1;;
  esac
done

GEMSET=`rvm-prompt g | sed -e 's/@//'`
export RAILS_ENV=cucumber

CONFIG="$( cd "$( dirname "$0" )" && pwd )"
CONFIG="$CONFIG/rbl-reinstall.rc"

if [ ! -f $CONFIG ]; then
    echo "$CONFIG does not exist"
    exit
fi

source $CONFIG

cd ~/redmine/$GEMSET

mysqldump -u root -p$DBROOTPW $GEMSET > ../setup/blcuke-salvage.sql
mysqladmin --force -u root -p$DBROOTPW drop $GEMSET
mysqladmin -u root -p$DBROOTPW create $GEMSET

zcat ../setup/$GEMSET.sql.gz| mysql -u root -p$DBROOTPW $GEMSET 

echo migrations
rake db:migrate
rake db:migrate_plugins
#rake redmine:backlogs:install batch=true corruptiontest=false labels=false RAILS_ENV=cucumber
rm -rf ~/$GEMSET/cache/*

rm -f log/cucumber.log
if [ -z "$TEST_FEATURE" ]; then
  echo "Running all tests"
  script -c "rake redmine:backlogs:rcov" -f ~/redmine/cuke-$GEMSET.log
else
  echo "Testing feature: $TEST_FEATURE"
  script -c "cucumber $TEST_FEATURE" -f ~/redmine/cuke-$GEMSET.log
fi

mysqladmin --force -u root -p$DBROOTPW drop $GEMSET
mysqladmin -u root -p$DBROOTPW create $GEMSET
cat ../setup/blcuke-salvage.sql | mysql -u root -p$DBROOTPW $GEMSET 

#rm -f ~/redmine/www.redminebacklogs.net/coverage/*
#cp -r ~/redmine/redmine/coverage/* ~/redmine/www.redminebacklogs.net/coverage
#chmod a+rwX ~/redmine/www.redminebacklogs.net/coverage/*
